# Specifies the API version being used for this Kubernetes resource.
apiVersion: apps/v1

# Specifies the type of resource, which is a "Deployment" in this case.
kind: Deployment

metadata:
  # Name for this Deployment resource.
  name: karsajobs-ui

  # Namespace in which the Deployment will be created.
  namespace: wush

  # Labels are key-value pairs used for organizing and selecting objects.
  # Here, we label this Deployment as part of the "frontend" application.
  labels:
    app: frontend

spec:
  # The number of desired replicas (pods) for this Deployment.
  replicas: 1

  # Defines a label selector to match pods that this Deployment manages.
  selector:
    matchLabels:
      app: frontend

  # Describes the pod template that this Deployment will create.
  template:
    metadata:
      # Labels applied to pods created from this template.
      labels:
        app: frontend

    spec:
      # List of containers within the pod.
      containers:
        # Name of the container.
        - name: karsajobs-ui
          # Docker image to be used for this container.
          image: ghcr.io/wussh/a433-microservices:karsajobs-ui

          # Defines when the image should be pulled. "IfNotPresent" means pull if not already on the node.
          imagePullPolicy: IfNotPresent

          # Compute resources required by this container.
          resources:
            # Limits describe the maximum amount of compute resources allowed.
            limits:
              # Memory/RAM to be used. "1Gi" means 1 gigabyte.
              memory: "1Gi"
              # CPU size to be used. "750m" means 750 milli-CPU or 3/4 of a CPU core.
              cpu: "750m"

          # Ports to be exposed from the container.
          ports:
            # Specifies the container port to expose on the pod's IP address.
            - containerPort: 8000

          # List of environment variables to set within the container.
          env:
            - name: VUE_APP_BACKEND
              # Change this value to specify the IP and port where your backend is running.
              value: http://127.0.0.1:44525
