# Specifies the API version being used for this Kubernetes resource.
apiVersion: v1

# Specifies the type of resource, which is a "Service" in this case.
kind: Service

metadata:
  # Name for this Service resource.
  name: karsajobs

  # Namespace in which the Service will be created.
  namespace: wush

  # Labels are key-value pairs used for organizing and selecting objects.
  # Here, we label this Service as part of the "backend" application.
  labels:
    app: backend

spec:
  # Defines a label selector to match pods that this Service should expose.
  selector:
    app: backend

  # List of ports to be exposed by this Service.
  ports:
    # Specifies the port number that will be exposed by this Service.
    - port: 8080

  # Specifies the type of Service to expose:
  # - NodePort: Exposes the Service on a port across all nodes in the cluster.
  type: NodePort
