# Specifies the API version being used for this Kubernetes resource.
apiVersion: v1

# Specifies the type of resource, which is a "Service" in this case.
kind: Service

metadata:
  # Name for this Service resource.
  name: mongo

  # Namespace in which the Service will be created.
  namespace: wush

  # Labels are key-value pairs used for organizing and selecting objects.
  # Here, we label this Service as part of the "mongo" application.
  labels:
    app: mongo

spec:
  # Defines a label selector to match pods that this Service should expose.
  selector:
    app: mongo

  # List of ports to be exposed by this Service.
  ports:
    # Specifies the port number that will be exposed by this Service.
    - port: 27017

  # The "clusterIP" setting is set to "None," which means the Service won't be accessible via a cluster IP address.
  # This is often used for headless services when you don't need a stable IP.
  clusterIP: None
