# API version
apiVersion: v1

# Kind is a string value representing the REST resource this object represents
# Secret holds secret data of a certain type
kind: Secret

metadata:
  # Name of the secret
  name: mongo-secret
  # # Secret namespace
  namespace: wush

# Used to facilitate programmatic handling of secret data
type: Opaque

# Secret data to be stored
data:
  MONGO_ROOT_USERNAME: cm9vdAo=
  MONGO_ROOT_PASSWORD: dG9vcgo=
  