# API version
apiVersion: v1

# Kind is a string value representing the REST resource this object represents
# ConfigMap holds configuration data for pods to consume.
kind: ConfigMap

metadata:
  # Name of the ConfigMap
  name: mongo-config
  # ConfigMap namespace
  namespace: wush

# Data contains the configuration data
data:
  # Name of the configuration will be created
  mongo.conf: |
    storage:
      dbpath: /data/db