# Specifies the API version being used for this Kubernetes resource.
apiVersion: v1

# Specifies the type of resource, which is a "Secret" in this case.
kind: Secret

metadata:
  # Name for this Secret resource.
  name: mongo-secret

  # Namespace in which the Secret will be created.
  namespace: wush

# Used to define the type of data stored in the Secret.
type: Opaque

# Secret data to be stored, encoded in base64 format.
data:
  # Specifies the username for the MongoDB root user.
  MONGO_ROOT_USERNAME: cm9vdAo=  # base64-encoded string

  # Specifies the password for the MongoDB root user.
  MONGO_ROOT_PASSWORD: dG9vcgo=  # base64-encoded string
