# Specifies the API version being used for this Kubernetes resource.
apiVersion: v1

# Specifies the type of resource, which is a "ConfigMap" in this case.
kind: ConfigMap

metadata:
  # Name for this ConfigMap resource.
  name: mongo-config

  # Namespace in which the ConfigMap will be created.
  namespace: wush

# Data contains the configuration data.
data:
  # Specifies the name of the configuration that will be created.
  mongo.conf: |
    # Configuration for MongoDB
    storage:
      # Specifies the database path where MongoDB will store its data.
      dbpath: /data/db
